name       : scrot
version    : '1.7'
release    : 9
source     :
    - https://github.com/resurrecting-open-source-projects/scrot/archive/1.7.tar.gz : e4ff764f93ea98018d46192c35bd34eeb577040ac6e217aa0d83b2a63d88f66b
license    : MIT
component  : system.utils
summary    : scrot (SCReen shOT) is a simple commandline screen capture utility
description: |
    scrot (SCReen shOT) is a simple commandline screen capture utility that uses imlib2 to grab and save images. Multiple image formats are supported through imlib2's dynamic saver modules.
builddeps  :
    - pkgconfig(harfbuzz)
    - pkgconfig(imlib2)
    - pkgconfig(libbsd)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xext)
    - autoconf-archive
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
