name       : scrot
version    : '1.2'
release    : 7
source     :
    - https://github.com/resurrecting-open-source-projects/scrot/archive/1.2.tar.gz : e9b41d4cb9b5ab3747d6718c4eb51d5aaf35b6cac23c9ff68af15fc1c9ce187c
license    : MIT
component  : system.utils
summary    : scrot (SCReen shOT) is a simple commandline screen capture utility
description: |
    scrot (SCReen shOT) is a simple commandline screen capture utility that uses imlib2 to grab and save images. Multiple image formats are supported through imlib2's dynamic saver modules.
builddeps  :
    - pkgconfig(giblib)
    - pkgconfig(harfbuzz)
    - pkgconfig(imlib2)
    - pkgconfig(xcursor)
    - autoconf-archive
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
